# Generated by Django 4.2.4 on 2023-08-15 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-visit',), 'verbose_name_plural': 'visitors'},
        ),
    ]
